version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: payment-platform-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: miroj
      POSTGRES_PASSWORD: miroj
      POSTGRES_DB: payment_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: